defmodule QRZ.Schema.Callsign do
  import DataSchema, only: [data_schema: 1]

  @data_accessor QRZ.XpathAccessor

  data_schema(
    field: {:call, "/QRZDatabase/Callsign/call/text()", &{:ok, to_string(&1)}},
    field: {:xref, "/QRZDatabase/Callsign/xref/text()", &{:ok, to_string(&1)}},
    field: {:aliases, "/QRZDatabase/Callsign/aliases/text()", &{:ok, to_string(&1)}},
    field: {:dxcc, "/QRZDatabase/Callsign/dxcc/text()", &{:ok, to_string(&1)}},
    field: {:first_name, "/QRZDatabase/Callsign/fname/text()", &{:ok, to_string(&1)}},
    field: {:last_name, "/QRZDatabase/Callsign/name/text()", &{:ok, to_string(&1)}},
    field: {:addr1, "/QRZDatabase/Callsign/addr1/text()", &{:ok, to_string(&1)}},
    field: {:addr2, "/QRZDatabase/Callsign/addr2/text()", &{:ok, to_string(&1)}},
    field: {:state, "/QRZDatabase/Callsign/state/text()", &{:ok, to_string(&1)}},
    field: {:zip, "/QRZDatabase/Callsign/zip/text()", &{:ok, to_string(&1)}},
    field: {:country, "/QRZDatabase/Callsign/country/text()", &{:ok, to_string(&1)}},
    field: {:ccode, "/QRZDatabase/Callsign/ccode/text()", &{:ok, to_string(&1)}},
    field: {:lat, "/QRZDatabase/Callsign/lat/text()", &{:ok, to_string(&1)}},
    field: {:lon, "/QRZDatabase/Callsign/lon/text()", &{:ok, to_string(&1)}},
    field: {:grid, "/QRZDatabase/Callsign/grid/text()", &{:ok, to_string(&1)}},
    field: {:county, "/QRZDatabase/Callsign/county/text()", &{:ok, to_string(&1)}},
    field: {:fips, "/QRZDatabase/Callsign/fips/text()", &{:ok, to_string(&1)}},
    field: {:land, "/QRZDatabase/Callsign/land/text()", &{:ok, to_string(&1)}},
    field: {:ef_date, "/QRZDatabase/Callsign/efdate/text()", &{:ok, to_string(&1)}},
    field: {:exp_date, "/QRZDatabase/Callsign/expdate/text()", &{:ok, to_string(&1)}},
    field: {:p_call, "/QRZDatabase/Callsign/p_call/text()", &{:ok, to_string(&1)}},
    field: {:class, "/QRZDatabase/Callsign/class/text()", &{:ok, to_string(&1)}},
    field: {:codes, "/QRZDatabase/Callsign/codes/text()", &{:ok, to_string(&1)}},
    field: {:qsl_mgr, "/QRZDatabase/Callsign/qslmgr/text()", &{:ok, to_string(&1)}},
    field: {:email, "/QRZDatabase/Callsign/email/text()", &{:ok, to_string(&1)}},
    field: {:url, "/QRZDatabase/Callsign/url/text()", &{:ok, to_string(&1)}},
    field: {:u_views, "/QRZDatabase/Callsign/u_views/text()", &{:ok, to_string(&1)}},
    field: {:bio, "/QRZDatabase/Callsign/bio/text()", &{:ok, to_string(&1)}},
    field: {:image, "/QRZDatabase/Callsign/image/text()", &{:ok, to_string(&1)}},
    field: {:image_info, "/QRZDatabase/Callsign/imageinfo/text()", &{:ok, to_string(&1)}},
    field: {:serial, "/QRZDatabase/Callsign/serial/text()", &{:ok, to_string(&1)}},
    field: {:mod_date, "/QRZDatabase/Callsign/moddate/text()", &{:ok, to_string(&1)}},
    field: {:msa, "/QRZDatabase/Callsign/MSA/text()", &{:ok, to_string(&1)}},
    field: {:area_code, "/QRZDatabase/Callsign/AreaCode/text()", &{:ok, to_string(&1)}},
    field: {:timezone, "/QRZDatabase/Callsign/TimeZone/text()", &{:ok, to_string(&1)}},
    field: {:gmt_offset, "/QRZDatabase/Callsign/GMTOffset/text()", &{:ok, to_string(&1)}},
    field: {:dst, "/QRZDatabase/Callsign/DST/text()", &{:ok, to_string(&1)}},
    field: {:eqsl, "/QRZDatabase/Callsign/eqsl/text()", &{:ok, to_string(&1)}},
    field: {:mqsl, "/QRZDatabase/Callsign/mqsl/text()", &{:ok, to_string(&1)}},
    field: {:cq_zone, "/QRZDatabase/Callsign/cqzone/text()", &{:ok, to_string(&1)}},
    field: {:itu_zone, "/QRZDatabase/Callsign/ituzone/text()", &{:ok, to_string(&1)}},
    field: {:born, "/QRZDatabase/Callsign/born/text()", &{:ok, to_string(&1)}},
    field: {:user, "/QRZDatabase/Callsign/user/text()", &{:ok, to_string(&1)}},
    field: {:lotw, "/QRZDatabase/Callsign/lotw/text()", &{:ok, to_string(&1)}},
    field: {:iota, "/QRZDatabase/Callsign/iota/text()", &{:ok, to_string(&1)}},
    field: {:geoloc, "/QRZDatabase/Callsign/geoloc/text()", &{:ok, to_string(&1)}},
    field: {:attn, "/QRZDatabase/Callsign/attn/text()", &{:ok, to_string(&1)}},
    field: {:nickname, "/QRZDatabase/Callsign/nickname/text()", &{:ok, to_string(&1)}},
    field: {:name_fmt, "/QRZDatabase/Callsign/name_fmt/text()", &{:ok, to_string(&1)}}
  )
end
